### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by EduardNN** [BerndCirotzki/ESP32_Precision-9_compass_BNO055#1]
Hi Bernd. I'm trying to repeat your project, but the compilation fails. Can you please tell me what versions of the IDE and libraries you are using?

**Comment by BerndCirotzki** [comment]
Hi EduardNN,
I don't know what compiler error you have ? , but delete the files "N2kMessages.cpp" and "N2kMessages.h" from the
NMEA2000 Library from timo and
add "bool getSensorMagneticOffsets(adafruit_bno055_offsets_t &offsets_type);" to the public in file "Adafruit_BNO055.h" could help.

**Comment by EduardNN** [comment]
Thank you very much for the help. I followed your advice but still getting the error.

exit status 1

Compilation error: 'tN2kAISTranceiverInfo' has not been declared


Are used:
Arduino IDE v2.0.4

library EEPROM at version 2.0.0 
library Wire at version 2.0.0
library Adafruit Unified Sensor at version 1.1.9 
library Adafruit BNO055 at version 1.6.1
library Adafruit BusIO at version 1.14.1
library NMEA2000 at version 4.18.7 
library NMEA2000_esp32 at version 1.0.3
library BluetoothSerial at version 2.0.0
library SPI at version 2.0.

**Comment by BerndCirotzki** [comment]
Hi EduardNN,
I added a complete new Version with some new thinks. I have been a litte careless with this repository... sorry. The file "N2kMessages.h" and ".cpp" are no longer needed, because Timo L. has correted the error in his original File. So use the complete NMEA2000 Library. But the Adafuit_BNO055 has the discribed changes.

I hope it will work now.
Bernd

**Comment by EduardNN** [comment]
Many thanks to Bernd for your help. The new version of the code compiles without errors. Adafuit_BNO055 libraries newer than 1.5.3 series, even with the addition of "bool getSensorMagneticOffsets(adafruit_bno055_offsets_t &offsets_type);", result in a compilation error. I hope this year, thanks to you, I will go fishing with a course indicator)))
Health and success to you. Thanks again.

**Comment by EduardNN** [comment]
Dear Bernd. Could you explain in more detail how to set up and calibrate the compass? Is it possible to set the Bluetooth code to a permanent PIN code? It is extremely inconvenient to confirm the connection when creating a pair of bluetooth devices, through the terminal on the computer ...
  Thank you very much for your support.

**Comment by BerndCirotzki** [comment]
calibrating a BNO055 :
https://www.youtube.com/watch?v=yPfQK75dZbU (one example ... the web is full with explaining please search yourself)
 
You only have to make the Bluetooth pairing once. then the device is known the next time ... But ?!? change the code as you want and build as you like!
